Handle multiple codecs in renegotiation
livekit/livekit-server pull request #191
Opened 2021-11-15 07:13 UTC by cnderrauber

update pion to v3.1.9 for answer same order of codec as publisher.
register enable codecs in subscriber peerconnectin created.

2021-11-15 07:14 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/livekit/livekit-server?pullRequest=191) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/livekit/livekit-server?pullRequest=191) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/livekit/livekit-server?pullRequest=191) it.</sub>

2021-11-15 10:42 UTC, boks1971 approved these changes
Let get some H264 flowing :-)

@cnderrauber There is a place in sfu.DownTrack where we send canned 1x1 frame. I was using the bytes you generated via ffmpeg for VP8 for that. We will have to add support for H.264 there.

2021-11-15 11:52 UTC, cnderrauber commented on pkg/config/config.go
> +			SmoothIntervals: 2,
Test found that SmoothInterval set to 4 willl cause the speaker state reaction  a little slow. I have test set default to 2 will more sensitive. But don't know is there other reason to set SmoothIntervals to 4, if it has, can revert this change

2021-11-15 17:37 UTC, davidzhao requested changes
this looks great! awesome work on the audio level change too.

two asks:
1. could you split them into different PRs? this will make it easier to keep track of and revert if found problematic
2. could you add an integration test case for multiple codec types, it could work like this:
    * two clients in the room
    * client A publishes vp8, client B receives it
    * client A publishes h.264, client B receives it as well.

2021-11-16 08:45 UTC, cnderrauber commented on pkg/rtc/mediatrack.go
> +	buff.Bind(receiver.GetParameters(), track.Codec().RTPCodecCapability, buffer.Options{
buff should use codec of TrackRemote it received

2021-11-16 08:46 UTC, cnderrauber commented
> this looks great! awesome work on the audio level change too.
> 
> two asks:
> 
> 1. could you split them into different PRs? this will make it easier to keep track of and revert if found problematic
> 2. could you add an integration test case for multiple codec types, it could work like this:
>    
>    * two clients in the room
>    * client A publishes vp8, client B receives it
>    * client A publishes h.264, client B receives it as well.

Test case added. Will open another pr for audio level with dtx

2021-11-17 12:29 UTC, boks1971 commented on pkg/sfu/buffer/buffer_test.go
> +		Codecs:           []webrtc.RTPCodecParameters{opusCodec},
Nice cleanup!

2021-11-17 12:31 UTC, boks1971 commented on pkg/sfu/downtrack.go
> +	buf := make([]byte, 1462)
boy, H.264 bitstream is complex. Thank you for putting this together.

2021-11-17 12:38 UTC, boks1971 commented on test/singlenode_test.go
> +	}
Good one @cnderrauber

2021-11-17 12:38 UTC, boks1971 approved these changes
This is great Jie! Let's do some H.264.....

2021-11-17 13:18 UTC, merged